// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: market_analyzer.proto

package marketanalyzerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceSource int32

const (
	PriceSource_PRICE_SOURCE_UNSPECIFIED PriceSource = 0
	PriceSource_PRICE_SOURCE_CLOSE       PriceSource = 1
	PriceSource_PRICE_SOURCE_HIGH_LOW    PriceSource = 2
)

// Enum value maps for PriceSource.
var (
	PriceSource_name = map[int32]string{
		0: "PRICE_SOURCE_UNSPECIFIED",
		1: "PRICE_SOURCE_CLOSE",
		2: "PRICE_SOURCE_HIGH_LOW",
	}
	PriceSource_value = map[string]int32{
		"PRICE_SOURCE_UNSPECIFIED": 0,
		"PRICE_SOURCE_CLOSE":       1,
		"PRICE_SOURCE_HIGH_LOW":    2,
	}
)

func (x PriceSource) Enum() *PriceSource {
	p := new(PriceSource)
	*p = x
	return p
}

func (x PriceSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceSource) Descriptor() protoreflect.EnumDescriptor {
	return file_market_analyzer_proto_enumTypes[0].Descriptor()
}

func (PriceSource) Type() protoreflect.EnumType {
	return &file_market_analyzer_proto_enumTypes[0]
}

func (x PriceSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceSource.Descriptor instead.
func (PriceSource) EnumDescriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{0}
}

type ExtremumKind int32

const (
	ExtremumKind_EXTREMUM_KIND_UNSPECIFIED ExtremumKind = 0
	ExtremumKind_EXTREMUM_KIND_HIGH        ExtremumKind = 1
	ExtremumKind_EXTREMUM_KIND_LOW         ExtremumKind = 2
)

// Enum value maps for ExtremumKind.
var (
	ExtremumKind_name = map[int32]string{
		0: "EXTREMUM_KIND_UNSPECIFIED",
		1: "EXTREMUM_KIND_HIGH",
		2: "EXTREMUM_KIND_LOW",
	}
	ExtremumKind_value = map[string]int32{
		"EXTREMUM_KIND_UNSPECIFIED": 0,
		"EXTREMUM_KIND_HIGH":        1,
		"EXTREMUM_KIND_LOW":         2,
	}
)

func (x ExtremumKind) Enum() *ExtremumKind {
	p := new(ExtremumKind)
	*p = x
	return p
}

func (x ExtremumKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtremumKind) Descriptor() protoreflect.EnumDescriptor {
	return file_market_analyzer_proto_enumTypes[1].Descriptor()
}

func (ExtremumKind) Type() protoreflect.EnumType {
	return &file_market_analyzer_proto_enumTypes[1]
}

func (x ExtremumKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtremumKind.Descriptor instead.
func (ExtremumKind) EnumDescriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{1}
}

type TrendState int32

const (
	TrendState_TREND_STATE_UNSPECIFIED  TrendState = 0
	TrendState_TREND_STATE_UP           TrendState = 1
	TrendState_TREND_STATE_DOWN         TrendState = 2
	TrendState_TREND_STATE_SIDEWAYS     TrendState = 3
	TrendState_TREND_STATE_UNDETERMINED TrendState = 4
)

// Enum value maps for TrendState.
var (
	TrendState_name = map[int32]string{
		0: "TREND_STATE_UNSPECIFIED",
		1: "TREND_STATE_UP",
		2: "TREND_STATE_DOWN",
		3: "TREND_STATE_SIDEWAYS",
		4: "TREND_STATE_UNDETERMINED",
	}
	TrendState_value = map[string]int32{
		"TREND_STATE_UNSPECIFIED":  0,
		"TREND_STATE_UP":           1,
		"TREND_STATE_DOWN":         2,
		"TREND_STATE_SIDEWAYS":     3,
		"TREND_STATE_UNDETERMINED": 4,
	}
)

func (x TrendState) Enum() *TrendState {
	p := new(TrendState)
	*p = x
	return p
}

func (x TrendState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrendState) Descriptor() protoreflect.EnumDescriptor {
	return file_market_analyzer_proto_enumTypes[2].Descriptor()
}

func (TrendState) Type() protoreflect.EnumType {
	return &file_market_analyzer_proto_enumTypes[2]
}

func (x TrendState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrendState.Descriptor instead.
func (TrendState) EnumDescriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{2}
}

type ZoneRole int32

const (
	ZoneRole_ZONE_ROLE_UNSPECIFIED ZoneRole = 0
	ZoneRole_ZONE_ROLE_SUPPORT     ZoneRole = 1
	ZoneRole_ZONE_ROLE_RESISTANCE  ZoneRole = 2
	ZoneRole_ZONE_ROLE_AT_PRICE    ZoneRole = 3
)

// Enum value maps for ZoneRole.
var (
	ZoneRole_name = map[int32]string{
		0: "ZONE_ROLE_UNSPECIFIED",
		1: "ZONE_ROLE_SUPPORT",
		2: "ZONE_ROLE_RESISTANCE",
		3: "ZONE_ROLE_AT_PRICE",
	}
	ZoneRole_value = map[string]int32{
		"ZONE_ROLE_UNSPECIFIED": 0,
		"ZONE_ROLE_SUPPORT":     1,
		"ZONE_ROLE_RESISTANCE":  2,
		"ZONE_ROLE_AT_PRICE":    3,
	}
)

func (x ZoneRole) Enum() *ZoneRole {
	p := new(ZoneRole)
	*p = x
	return p
}

func (x ZoneRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneRole) Descriptor() protoreflect.EnumDescriptor {
	return file_market_analyzer_proto_enumTypes[3].Descriptor()
}

func (ZoneRole) Type() protoreflect.EnumType {
	return &file_market_analyzer_proto_enumTypes[3]
}

func (x ZoneRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneRole.Descriptor instead.
func (ZoneRole) EnumDescriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{3}
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	Market        *string                `protobuf:"bytes,2,opt,name=market,proto3,oneof" json:"market,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	CandleCount   *uint32                `protobuf:"varint,5,opt,name=candle_count,json=candleCount,proto3,oneof" json:"candle_count,omitempty"`
	Interval      *string                `protobuf:"bytes,6,opt,name=interval,proto3,oneof" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_market_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *Selection) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *Selection) GetMarket() string {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return ""
}

func (x *Selection) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *Selection) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Selection) GetCandleCount() uint32 {
	if x != nil && x.CandleCount != nil {
		return *x.CandleCount
	}
	return 0
}

func (x *Selection) GetInterval() string {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return ""
}

type ATRSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *uint32                `protobuf:"varint,1,opt,name=period,proto3,oneof" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATRSettings) Reset() {
	*x = ATRSettings{}
	mi := &file_market_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATRSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATRSettings) ProtoMessage() {}

func (x *ATRSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATRSettings.ProtoReflect.Descriptor instead.
func (*ATRSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *ATRSettings) GetPeriod() uint32 {
	if x != nil && x.Period != nil {
		return *x.Period
	}
	return 0
}

type LocalExtremaSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PivotSpan     *uint32                `protobuf:"varint,1,opt,name=pivot_span,json=pivotSpan,proto3,oneof" json:"pivot_span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalExtremaSettings) Reset() {
	*x = LocalExtremaSettings{}
	mi := &file_market_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExtremaSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExtremaSettings) ProtoMessage() {}

func (x *LocalExtremaSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExtremaSettings.ProtoReflect.Descriptor instead.
func (*LocalExtremaSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *LocalExtremaSettings) GetPivotSpan() uint32 {
	if x != nil && x.PivotSpan != nil {
		return *x.PivotSpan
	}
	return 0
}

type PercentReversalSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReversalPct   *string                `protobuf:"bytes,1,opt,name=reversal_pct,json=reversalPct,proto3,oneof" json:"reversal_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PercentReversalSettings) Reset() {
	*x = PercentReversalSettings{}
	mi := &file_market_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PercentReversalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentReversalSettings) ProtoMessage() {}

func (x *PercentReversalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentReversalSettings.ProtoReflect.Descriptor instead.
func (*PercentReversalSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *PercentReversalSettings) GetReversalPct() string {
	if x != nil && x.ReversalPct != nil {
		return *x.ReversalPct
	}
	return ""
}

type ATRReversalSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtrPeriod     *uint32                `protobuf:"varint,1,opt,name=atr_period,json=atrPeriod,proto3,oneof" json:"atr_period,omitempty"`
	AtrMultiplier *string                `protobuf:"bytes,2,opt,name=atr_multiplier,json=atrMultiplier,proto3,oneof" json:"atr_multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATRReversalSettings) Reset() {
	*x = ATRReversalSettings{}
	mi := &file_market_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATRReversalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATRReversalSettings) ProtoMessage() {}

func (x *ATRReversalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATRReversalSettings.ProtoReflect.Descriptor instead.
func (*ATRReversalSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *ATRReversalSettings) GetAtrPeriod() uint32 {
	if x != nil && x.AtrPeriod != nil {
		return *x.AtrPeriod
	}
	return 0
}

func (x *ATRReversalSettings) GetAtrMultiplier() string {
	if x != nil && x.AtrMultiplier != nil {
		return *x.AtrMultiplier
	}
	return ""
}

type ExtremaSettings struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PriceSource *PriceSource           `protobuf:"varint,1,opt,name=price_source,json=priceSource,proto3,enum=marketanalyzer.v1.PriceSource,oneof" json:"price_source,omitempty"`
	// Types that are valid to be assigned to Method:
	//
	//	*ExtremaSettings_LocalExtrema
	//	*ExtremaSettings_ReversalPercent
	//	*ExtremaSettings_ReversalAtr
	Method        isExtremaSettings_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtremaSettings) Reset() {
	*x = ExtremaSettings{}
	mi := &file_market_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtremaSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtremaSettings) ProtoMessage() {}

func (x *ExtremaSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtremaSettings.ProtoReflect.Descriptor instead.
func (*ExtremaSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{5}
}

func (x *ExtremaSettings) GetPriceSource() PriceSource {
	if x != nil && x.PriceSource != nil {
		return *x.PriceSource
	}
	return PriceSource_PRICE_SOURCE_UNSPECIFIED
}

func (x *ExtremaSettings) GetMethod() isExtremaSettings_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *ExtremaSettings) GetLocalExtrema() *LocalExtremaSettings {
	if x != nil {
		if x, ok := x.Method.(*ExtremaSettings_LocalExtrema); ok {
			return x.LocalExtrema
		}
	}
	return nil
}

func (x *ExtremaSettings) GetReversalPercent() *PercentReversalSettings {
	if x != nil {
		if x, ok := x.Method.(*ExtremaSettings_ReversalPercent); ok {
			return x.ReversalPercent
		}
	}
	return nil
}

func (x *ExtremaSettings) GetReversalAtr() *ATRReversalSettings {
	if x != nil {
		if x, ok := x.Method.(*ExtremaSettings_ReversalAtr); ok {
			return x.ReversalAtr
		}
	}
	return nil
}

type isExtremaSettings_Method interface {
	isExtremaSettings_Method()
}

type ExtremaSettings_LocalExtrema struct {
	LocalExtrema *LocalExtremaSettings `protobuf:"bytes,2,opt,name=local_extrema,json=localExtrema,proto3,oneof"`
}

type ExtremaSettings_ReversalPercent struct {
	ReversalPercent *PercentReversalSettings `protobuf:"bytes,3,opt,name=reversal_percent,json=reversalPercent,proto3,oneof"`
}

type ExtremaSettings_ReversalAtr struct {
	ReversalAtr *ATRReversalSettings `protobuf:"bytes,4,opt,name=reversal_atr,json=reversalAtr,proto3,oneof"`
}

func (*ExtremaSettings_LocalExtrema) isExtremaSettings_Method() {}

func (*ExtremaSettings_ReversalPercent) isExtremaSettings_Method() {}

func (*ExtremaSettings_ReversalAtr) isExtremaSettings_Method() {}

type TrendSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Extrema              *ExtremaSettings       `protobuf:"bytes,1,opt,name=extrema,proto3" json:"extrema,omitempty"`
	EqualityTolerancePct *string                `protobuf:"bytes,2,opt,name=equality_tolerance_pct,json=equalityTolerancePct,proto3,oneof" json:"equality_tolerance_pct,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrendSettings) Reset() {
	*x = TrendSettings{}
	mi := &file_market_analyzer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendSettings) ProtoMessage() {}

func (x *TrendSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendSettings.ProtoReflect.Descriptor instead.
func (*TrendSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{6}
}

func (x *TrendSettings) GetExtrema() *ExtremaSettings {
	if x != nil {
		return x.Extrema
	}
	return nil
}

func (x *TrendSettings) GetEqualityTolerancePct() string {
	if x != nil && x.EqualityTolerancePct != nil {
		return *x.EqualityTolerancePct
	}
	return ""
}

type LevelSettings struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Extrema                *ExtremaSettings       `protobuf:"bytes,1,opt,name=extrema,proto3" json:"extrema,omitempty"`
	AtrPeriod              *uint32                `protobuf:"varint,2,opt,name=atr_period,json=atrPeriod,proto3,oneof" json:"atr_period,omitempty"`
	ZoneWidthAtr           *string                `protobuf:"bytes,3,opt,name=zone_width_atr,json=zoneWidthAtr,proto3,oneof" json:"zone_width_atr,omitempty"`
	MinTouches             *uint32                `protobuf:"varint,4,opt,name=min_touches,json=minTouches,proto3,oneof" json:"min_touches,omitempty"`
	MinTouchSeparationBars *uint32                `protobuf:"varint,5,opt,name=min_touch_separation_bars,json=minTouchSeparationBars,proto3,oneof" json:"min_touch_separation_bars,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LevelSettings) Reset() {
	*x = LevelSettings{}
	mi := &file_market_analyzer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelSettings) ProtoMessage() {}

func (x *LevelSettings) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelSettings.ProtoReflect.Descriptor instead.
func (*LevelSettings) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{7}
}

func (x *LevelSettings) GetExtrema() *ExtremaSettings {
	if x != nil {
		return x.Extrema
	}
	return nil
}

func (x *LevelSettings) GetAtrPeriod() uint32 {
	if x != nil && x.AtrPeriod != nil {
		return *x.AtrPeriod
	}
	return 0
}

func (x *LevelSettings) GetZoneWidthAtr() string {
	if x != nil && x.ZoneWidthAtr != nil {
		return *x.ZoneWidthAtr
	}
	return ""
}

func (x *LevelSettings) GetMinTouches() uint32 {
	if x != nil && x.MinTouches != nil {
		return *x.MinTouches
	}
	return 0
}

func (x *LevelSettings) GetMinTouchSeparationBars() uint32 {
	if x != nil && x.MinTouchSeparationBars != nil {
		return *x.MinTouchSeparationBars
	}
	return 0
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Open          string                 `protobuf:"bytes,3,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        string                 `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Turnover      string                 `protobuf:"bytes,8,opt,name=turnover,proto3" json:"turnover,omitempty"`
	TradesCount   *int64                 `protobuf:"varint,9,opt,name=trades_count,json=tradesCount,proto3,oneof" json:"trades_count,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_market_analyzer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{8}
}

func (x *Candle) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *Candle) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *Candle) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Candle) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Candle) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Candle) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Candle) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Candle) GetTurnover() string {
	if x != nil {
		return x.Turnover
	}
	return ""
}

func (x *Candle) GetTradesCount() int64 {
	if x != nil && x.TradesCount != nil {
		return *x.TradesCount
	}
	return 0
}

func (x *Candle) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	EvaluatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	SourceFrom    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=source_from,json=sourceFrom,proto3" json:"source_from,omitempty"`
	SourceTo      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=source_to,json=sourceTo,proto3" json:"source_to,omitempty"`
	AlgorithmIds  []string               `protobuf:"bytes,5,rep,name=algorithm_ids,json=algorithmIds,proto3" json:"algorithm_ids,omitempty"`
	NumericPolicy string                 `protobuf:"bytes,6,opt,name=numeric_policy,json=numericPolicy,proto3" json:"numeric_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_market_analyzer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{9}
}

func (x *Metadata) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *Metadata) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *Metadata) GetSourceFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceFrom
	}
	return nil
}

func (x *Metadata) GetSourceTo() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceTo
	}
	return nil
}

func (x *Metadata) GetAlgorithmIds() []string {
	if x != nil {
		return x.AlgorithmIds
	}
	return nil
}

func (x *Metadata) GetNumericPolicy() string {
	if x != nil {
		return x.NumericPolicy
	}
	return ""
}

type ATRResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CandleIndex   uint32                 `protobuf:"varint,2,opt,name=candle_index,json=candleIndex,proto3" json:"candle_index,omitempty"`
	ValueTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=value_time,json=valueTime,proto3" json:"value_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATRResult) Reset() {
	*x = ATRResult{}
	mi := &file_market_analyzer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATRResult) ProtoMessage() {}

func (x *ATRResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATRResult.ProtoReflect.Descriptor instead.
func (*ATRResult) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{10}
}

func (x *ATRResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ATRResult) GetCandleIndex() uint32 {
	if x != nil {
		return x.CandleIndex
	}
	return 0
}

func (x *ATRResult) GetValueTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValueTime
	}
	return nil
}

type NATRResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Atr            string                 `protobuf:"bytes,2,opt,name=atr,proto3" json:"atr,omitempty"`
	ReferenceClose string                 `protobuf:"bytes,3,opt,name=reference_close,json=referenceClose,proto3" json:"reference_close,omitempty"`
	CandleIndex    uint32                 `protobuf:"varint,4,opt,name=candle_index,json=candleIndex,proto3" json:"candle_index,omitempty"`
	ValueTime      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=value_time,json=valueTime,proto3" json:"value_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NATRResult) Reset() {
	*x = NATRResult{}
	mi := &file_market_analyzer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NATRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NATRResult) ProtoMessage() {}

func (x *NATRResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NATRResult.ProtoReflect.Descriptor instead.
func (*NATRResult) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{11}
}

func (x *NATRResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NATRResult) GetAtr() string {
	if x != nil {
		return x.Atr
	}
	return ""
}

func (x *NATRResult) GetReferenceClose() string {
	if x != nil {
		return x.ReferenceClose
	}
	return ""
}

func (x *NATRResult) GetCandleIndex() uint32 {
	if x != nil {
		return x.CandleIndex
	}
	return 0
}

func (x *NATRResult) GetValueTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValueTime
	}
	return nil
}

type ReversalEvidence struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Threshold         string                 `protobuf:"bytes,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	ConfirmationPrice string                 `protobuf:"bytes,2,opt,name=confirmation_price,json=confirmationPrice,proto3" json:"confirmation_price,omitempty"`
	CandidateAtr      *string                `protobuf:"bytes,3,opt,name=candidate_atr,json=candidateAtr,proto3,oneof" json:"candidate_atr,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReversalEvidence) Reset() {
	*x = ReversalEvidence{}
	mi := &file_market_analyzer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReversalEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReversalEvidence) ProtoMessage() {}

func (x *ReversalEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReversalEvidence.ProtoReflect.Descriptor instead.
func (*ReversalEvidence) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{12}
}

func (x *ReversalEvidence) GetThreshold() string {
	if x != nil {
		return x.Threshold
	}
	return ""
}

func (x *ReversalEvidence) GetConfirmationPrice() string {
	if x != nil {
		return x.ConfirmationPrice
	}
	return ""
}

func (x *ReversalEvidence) GetCandidateAtr() string {
	if x != nil && x.CandidateAtr != nil {
		return *x.CandidateAtr
	}
	return ""
}

type Extremum struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Kind                    ExtremumKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=marketanalyzer.v1.ExtremumKind" json:"kind,omitempty"`
	CandleIndex             uint32                 `protobuf:"varint,2,opt,name=candle_index,json=candleIndex,proto3" json:"candle_index,omitempty"`
	Time                    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Price                   string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	ConfirmationCandleIndex uint32                 `protobuf:"varint,5,opt,name=confirmation_candle_index,json=confirmationCandleIndex,proto3" json:"confirmation_candle_index,omitempty"`
	ConfirmationTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=confirmation_time,json=confirmationTime,proto3" json:"confirmation_time,omitempty"`
	Reversal                *ReversalEvidence      `protobuf:"bytes,7,opt,name=reversal,proto3" json:"reversal,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Extremum) Reset() {
	*x = Extremum{}
	mi := &file_market_analyzer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extremum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extremum) ProtoMessage() {}

func (x *Extremum) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extremum.ProtoReflect.Descriptor instead.
func (*Extremum) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{13}
}

func (x *Extremum) GetKind() ExtremumKind {
	if x != nil {
		return x.Kind
	}
	return ExtremumKind_EXTREMUM_KIND_UNSPECIFIED
}

func (x *Extremum) GetCandleIndex() uint32 {
	if x != nil {
		return x.CandleIndex
	}
	return 0
}

func (x *Extremum) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Extremum) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Extremum) GetConfirmationCandleIndex() uint32 {
	if x != nil {
		return x.ConfirmationCandleIndex
	}
	return 0
}

func (x *Extremum) GetConfirmationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmationTime
	}
	return nil
}

func (x *Extremum) GetReversal() *ReversalEvidence {
	if x != nil {
		return x.Reversal
	}
	return nil
}

type ExtremaResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Extremum            `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtremaResult) Reset() {
	*x = ExtremaResult{}
	mi := &file_market_analyzer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtremaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtremaResult) ProtoMessage() {}

func (x *ExtremaResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtremaResult.ProtoReflect.Descriptor instead.
func (*ExtremaResult) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{14}
}

func (x *ExtremaResult) GetPoints() []*Extremum {
	if x != nil {
		return x.Points
	}
	return nil
}

type TrendResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          TrendState             `protobuf:"varint,1,opt,name=state,proto3,enum=marketanalyzer.v1.TrendState" json:"state,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Tolerance      string                 `protobuf:"bytes,3,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	ReferenceClose string                 `protobuf:"bytes,4,opt,name=reference_close,json=referenceClose,proto3" json:"reference_close,omitempty"`
	Extrema        *ExtremaResult         `protobuf:"bytes,5,opt,name=extrema,proto3" json:"extrema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrendResult) Reset() {
	*x = TrendResult{}
	mi := &file_market_analyzer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendResult) ProtoMessage() {}

func (x *TrendResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendResult.ProtoReflect.Descriptor instead.
func (*TrendResult) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{15}
}

func (x *TrendResult) GetState() TrendState {
	if x != nil {
		return x.State
	}
	return TrendState_TREND_STATE_UNSPECIFIED
}

func (x *TrendResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TrendResult) GetTolerance() string {
	if x != nil {
		return x.Tolerance
	}
	return ""
}

func (x *TrendResult) GetReferenceClose() string {
	if x != nil {
		return x.ReferenceClose
	}
	return ""
}

func (x *TrendResult) GetExtrema() *ExtremaResult {
	if x != nil {
		return x.Extrema
	}
	return nil
}

type PriceZone struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LowerBound            string                 `protobuf:"bytes,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound            string                 `protobuf:"bytes,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	RepresentativePrice   string                 `protobuf:"bytes,3,opt,name=representative_price,json=representativePrice,proto3" json:"representative_price,omitempty"`
	Role                  ZoneRole               `protobuf:"varint,4,opt,name=role,proto3,enum=marketanalyzer.v1.ZoneRole" json:"role,omitempty"`
	ExtremumIndices       []uint32               `protobuf:"varint,5,rep,packed,name=extremum_indices,json=extremumIndices,proto3" json:"extremum_indices,omitempty"`
	AcceptedCandleIndices []uint32               `protobuf:"varint,6,rep,packed,name=accepted_candle_indices,json=acceptedCandleIndices,proto3" json:"accepted_candle_indices,omitempty"`
	TouchCount            uint32                 `protobuf:"varint,7,opt,name=touch_count,json=touchCount,proto3" json:"touch_count,omitempty"`
	FirstTouchTime        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=first_touch_time,json=firstTouchTime,proto3" json:"first_touch_time,omitempty"`
	LastTouchTime         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_touch_time,json=lastTouchTime,proto3" json:"last_touch_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PriceZone) Reset() {
	*x = PriceZone{}
	mi := &file_market_analyzer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceZone) ProtoMessage() {}

func (x *PriceZone) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceZone.ProtoReflect.Descriptor instead.
func (*PriceZone) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{16}
}

func (x *PriceZone) GetLowerBound() string {
	if x != nil {
		return x.LowerBound
	}
	return ""
}

func (x *PriceZone) GetUpperBound() string {
	if x != nil {
		return x.UpperBound
	}
	return ""
}

func (x *PriceZone) GetRepresentativePrice() string {
	if x != nil {
		return x.RepresentativePrice
	}
	return ""
}

func (x *PriceZone) GetRole() ZoneRole {
	if x != nil {
		return x.Role
	}
	return ZoneRole_ZONE_ROLE_UNSPECIFIED
}

func (x *PriceZone) GetExtremumIndices() []uint32 {
	if x != nil {
		return x.ExtremumIndices
	}
	return nil
}

func (x *PriceZone) GetAcceptedCandleIndices() []uint32 {
	if x != nil {
		return x.AcceptedCandleIndices
	}
	return nil
}

func (x *PriceZone) GetTouchCount() uint32 {
	if x != nil {
		return x.TouchCount
	}
	return 0
}

func (x *PriceZone) GetFirstTouchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTouchTime
	}
	return nil
}

func (x *PriceZone) GetLastTouchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTouchTime
	}
	return nil
}

type LevelsResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Zones            []*PriceZone           `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	Extrema          *ExtremaResult         `protobuf:"bytes,2,opt,name=extrema,proto3" json:"extrema,omitempty"`
	Atr              *ATRResult             `protobuf:"bytes,3,opt,name=atr,proto3" json:"atr,omitempty"`
	MaximumZoneWidth string                 `protobuf:"bytes,4,opt,name=maximum_zone_width,json=maximumZoneWidth,proto3" json:"maximum_zone_width,omitempty"`
	ReferenceClose   string                 `protobuf:"bytes,5,opt,name=reference_close,json=referenceClose,proto3" json:"reference_close,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LevelsResult) Reset() {
	*x = LevelsResult{}
	mi := &file_market_analyzer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelsResult) ProtoMessage() {}

func (x *LevelsResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelsResult.ProtoReflect.Descriptor instead.
func (*LevelsResult) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{17}
}

func (x *LevelsResult) GetZones() []*PriceZone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *LevelsResult) GetExtrema() *ExtremaResult {
	if x != nil {
		return x.Extrema
	}
	return nil
}

func (x *LevelsResult) GetAtr() *ATRResult {
	if x != nil {
		return x.Atr
	}
	return nil
}

func (x *LevelsResult) GetMaximumZoneWidth() string {
	if x != nil {
		return x.MaximumZoneWidth
	}
	return ""
}

func (x *LevelsResult) GetReferenceClose() string {
	if x != nil {
		return x.ReferenceClose
	}
	return ""
}

type GetATRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	Settings      *ATRSettings           `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetATRRequest) Reset() {
	*x = GetATRRequest{}
	mi := &file_market_analyzer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetATRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetATRRequest) ProtoMessage() {}

func (x *GetATRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetATRRequest.ProtoReflect.Descriptor instead.
func (*GetATRRequest) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{18}
}

func (x *GetATRRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *GetATRRequest) GetSettings() *ATRSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetATRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Candles       []*Candle              `protobuf:"bytes,2,rep,name=candles,proto3" json:"candles,omitempty"`
	Settings      *ATRSettings           `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Result        *ATRResult             `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetATRResponse) Reset() {
	*x = GetATRResponse{}
	mi := &file_market_analyzer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetATRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetATRResponse) ProtoMessage() {}

func (x *GetATRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetATRResponse.ProtoReflect.Descriptor instead.
func (*GetATRResponse) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{19}
}

func (x *GetATRResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetATRResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetATRResponse) GetSettings() *ATRSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetATRResponse) GetResult() *ATRResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetNATRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	Settings      *ATRSettings           `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNATRRequest) Reset() {
	*x = GetNATRRequest{}
	mi := &file_market_analyzer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNATRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNATRRequest) ProtoMessage() {}

func (x *GetNATRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNATRRequest.ProtoReflect.Descriptor instead.
func (*GetNATRRequest) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{20}
}

func (x *GetNATRRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *GetNATRRequest) GetSettings() *ATRSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetNATRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Candles       []*Candle              `protobuf:"bytes,2,rep,name=candles,proto3" json:"candles,omitempty"`
	Settings      *ATRSettings           `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Result        *NATRResult            `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNATRResponse) Reset() {
	*x = GetNATRResponse{}
	mi := &file_market_analyzer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNATRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNATRResponse) ProtoMessage() {}

func (x *GetNATRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNATRResponse.ProtoReflect.Descriptor instead.
func (*GetNATRResponse) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{21}
}

func (x *GetNATRResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetNATRResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetNATRResponse) GetSettings() *ATRSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetNATRResponse) GetResult() *NATRResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetExtremaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	Settings      *ExtremaSettings       `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtremaRequest) Reset() {
	*x = GetExtremaRequest{}
	mi := &file_market_analyzer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtremaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtremaRequest) ProtoMessage() {}

func (x *GetExtremaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtremaRequest.ProtoReflect.Descriptor instead.
func (*GetExtremaRequest) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{22}
}

func (x *GetExtremaRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *GetExtremaRequest) GetSettings() *ExtremaSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetExtremaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Candles       []*Candle              `protobuf:"bytes,2,rep,name=candles,proto3" json:"candles,omitempty"`
	Settings      *ExtremaSettings       `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Result        *ExtremaResult         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtremaResponse) Reset() {
	*x = GetExtremaResponse{}
	mi := &file_market_analyzer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtremaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtremaResponse) ProtoMessage() {}

func (x *GetExtremaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtremaResponse.ProtoReflect.Descriptor instead.
func (*GetExtremaResponse) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{23}
}

func (x *GetExtremaResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetExtremaResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetExtremaResponse) GetSettings() *ExtremaSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetExtremaResponse) GetResult() *ExtremaResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	Settings      *TrendSettings         `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendRequest) Reset() {
	*x = GetTrendRequest{}
	mi := &file_market_analyzer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendRequest) ProtoMessage() {}

func (x *GetTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendRequest.ProtoReflect.Descriptor instead.
func (*GetTrendRequest) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{24}
}

func (x *GetTrendRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *GetTrendRequest) GetSettings() *TrendSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Candles       []*Candle              `protobuf:"bytes,2,rep,name=candles,proto3" json:"candles,omitempty"`
	Settings      *TrendSettings         `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Result        *TrendResult           `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendResponse) Reset() {
	*x = GetTrendResponse{}
	mi := &file_market_analyzer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendResponse) ProtoMessage() {}

func (x *GetTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendResponse.ProtoReflect.Descriptor instead.
func (*GetTrendResponse) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{25}
}

func (x *GetTrendResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetTrendResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetTrendResponse) GetSettings() *TrendSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetTrendResponse) GetResult() *TrendResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetLevelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *Selection             `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	Settings      *LevelSettings         `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelsRequest) Reset() {
	*x = GetLevelsRequest{}
	mi := &file_market_analyzer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelsRequest) ProtoMessage() {}

func (x *GetLevelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelsRequest.ProtoReflect.Descriptor instead.
func (*GetLevelsRequest) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{26}
}

func (x *GetLevelsRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *GetLevelsRequest) GetSettings() *LevelSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetLevelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Candles       []*Candle              `protobuf:"bytes,2,rep,name=candles,proto3" json:"candles,omitempty"`
	Settings      *LevelSettings         `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Result        *LevelsResult          `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLevelsResponse) Reset() {
	*x = GetLevelsResponse{}
	mi := &file_market_analyzer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLevelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelsResponse) ProtoMessage() {}

func (x *GetLevelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelsResponse.ProtoReflect.Descriptor instead.
func (*GetLevelsResponse) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{27}
}

func (x *GetLevelsResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetLevelsResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *GetLevelsResponse) GetSettings() *LevelSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetLevelsResponse) GetResult() *LevelsResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ErrorDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Field          *string                `protobuf:"bytes,2,opt,name=field,proto3,oneof" json:"field,omitempty"`
	UpstreamCode   *string                `protobuf:"bytes,3,opt,name=upstream_code,json=upstreamCode,proto3,oneof" json:"upstream_code,omitempty"`
	UpstreamReason *string                `protobuf:"bytes,4,opt,name=upstream_reason,json=upstreamReason,proto3,oneof" json:"upstream_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_market_analyzer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_market_analyzer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_market_analyzer_proto_rawDescGZIP(), []int{28}
}

func (x *ErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorDetail) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *ErrorDetail) GetUpstreamCode() string {
	if x != nil && x.UpstreamCode != nil {
		return *x.UpstreamCode
	}
	return ""
}

func (x *ErrorDetail) GetUpstreamReason() string {
	if x != nil && x.UpstreamReason != nil {
		return *x.UpstreamReason
	}
	return ""
}

var File_market_analyzer_proto protoreflect.FileDescriptor

const file_market_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x15market_analyzer.proto\x12\x11marketanalyzer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\tSelection\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1b\n" +
	"\x06market\x18\x02 \x01(\tH\x01R\x06market\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x02R\x06symbol\x88\x01\x01\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12&\n" +
	"\fcandle_count\x18\x05 \x01(\rH\x03R\vcandleCount\x88\x01\x01\x12\x1f\n" +
	"\binterval\x18\x06 \x01(\tH\x04R\binterval\x88\x01\x01B\v\n" +
	"\t_exchangeB\t\n" +
	"\a_marketB\t\n" +
	"\a_symbolB\x0f\n" +
	"\r_candle_countB\v\n" +
	"\t_interval\"5\n" +
	"\vATRSettings\x12\x1b\n" +
	"\x06period\x18\x01 \x01(\rH\x00R\x06period\x88\x01\x01B\t\n" +
	"\a_period\"I\n" +
	"\x14LocalExtremaSettings\x12\"\n" +
	"\n" +
	"pivot_span\x18\x01 \x01(\rH\x00R\tpivotSpan\x88\x01\x01B\r\n" +
	"\v_pivot_span\"R\n" +
	"\x17PercentReversalSettings\x12&\n" +
	"\freversal_pct\x18\x01 \x01(\tH\x00R\vreversalPct\x88\x01\x01B\x0f\n" +
	"\r_reversal_pct\"\x87\x01\n" +
	"\x13ATRReversalSettings\x12\"\n" +
	"\n" +
	"atr_period\x18\x01 \x01(\rH\x00R\tatrPeriod\x88\x01\x01\x12*\n" +
	"\x0eatr_multiplier\x18\x02 \x01(\tH\x01R\ratrMultiplier\x88\x01\x01B\r\n" +
	"\v_atr_periodB\x11\n" +
	"\x0f_atr_multiplier\"\xea\x02\n" +
	"\x0fExtremaSettings\x12F\n" +
	"\fprice_source\x18\x01 \x01(\x0e2\x1e.marketanalyzer.v1.PriceSourceH\x01R\vpriceSource\x88\x01\x01\x12N\n" +
	"\rlocal_extrema\x18\x02 \x01(\v2'.marketanalyzer.v1.LocalExtremaSettingsH\x00R\flocalExtrema\x12W\n" +
	"\x10reversal_percent\x18\x03 \x01(\v2*.marketanalyzer.v1.PercentReversalSettingsH\x00R\x0freversalPercent\x12K\n" +
	"\freversal_atr\x18\x04 \x01(\v2&.marketanalyzer.v1.ATRReversalSettingsH\x00R\vreversalAtrB\b\n" +
	"\x06methodB\x0f\n" +
	"\r_price_source\"\xa3\x01\n" +
	"\rTrendSettings\x12<\n" +
	"\aextrema\x18\x01 \x01(\v2\".marketanalyzer.v1.ExtremaSettingsR\aextrema\x129\n" +
	"\x16equality_tolerance_pct\x18\x02 \x01(\tH\x00R\x14equalityTolerancePct\x88\x01\x01B\x19\n" +
	"\x17_equality_tolerance_pct\"\xd2\x02\n" +
	"\rLevelSettings\x12<\n" +
	"\aextrema\x18\x01 \x01(\v2\".marketanalyzer.v1.ExtremaSettingsR\aextrema\x12\"\n" +
	"\n" +
	"atr_period\x18\x02 \x01(\rH\x00R\tatrPeriod\x88\x01\x01\x12)\n" +
	"\x0ezone_width_atr\x18\x03 \x01(\tH\x01R\fzoneWidthAtr\x88\x01\x01\x12$\n" +
	"\vmin_touches\x18\x04 \x01(\rH\x02R\n" +
	"minTouches\x88\x01\x01\x12>\n" +
	"\x19min_touch_separation_bars\x18\x05 \x01(\rH\x03R\x16minTouchSeparationBars\x88\x01\x01B\r\n" +
	"\v_atr_periodB\x11\n" +
	"\x0f_zone_width_atrB\x0e\n" +
	"\f_min_touchesB\x1c\n" +
	"\x1a_min_touch_separation_bars\"\xf4\x02\n" +
	"\x06Candle\x127\n" +
	"\topen_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x129\n" +
	"\n" +
	"close_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12\x12\n" +
	"\x04open\x18\x03 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\tR\x06volume\x12\x1a\n" +
	"\bturnover\x18\b \x01(\tR\bturnover\x12&\n" +
	"\ftrades_count\x18\t \x01(\x03H\x00R\vtradesCount\x88\x01\x01\x129\n" +
	"\n" +
	"fetched_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAtB\x0f\n" +
	"\r_trades_count\"\xc7\x02\n" +
	"\bMetadata\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12=\n" +
	"\fevaluated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12;\n" +
	"\vsource_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sourceFrom\x127\n" +
	"\tsource_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsourceTo\x12#\n" +
	"\ralgorithm_ids\x18\x05 \x03(\tR\falgorithmIds\x12%\n" +
	"\x0enumeric_policy\x18\x06 \x01(\tR\rnumericPolicy\"\x7f\n" +
	"\tATRResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12!\n" +
	"\fcandle_index\x18\x02 \x01(\rR\vcandleIndex\x129\n" +
	"\n" +
	"value_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tvalueTime\"\xbb\x01\n" +
	"\n" +
	"NATRResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03atr\x18\x02 \x01(\tR\x03atr\x12'\n" +
	"\x0freference_close\x18\x03 \x01(\tR\x0ereferenceClose\x12!\n" +
	"\fcandle_index\x18\x04 \x01(\rR\vcandleIndex\x129\n" +
	"\n" +
	"value_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvalueTime\"\x9b\x01\n" +
	"\x10ReversalEvidence\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\tR\tthreshold\x12-\n" +
	"\x12confirmation_price\x18\x02 \x01(\tR\x11confirmationPrice\x12(\n" +
	"\rcandidate_atr\x18\x03 \x01(\tH\x00R\fcandidateAtr\x88\x01\x01B\x10\n" +
	"\x0e_candidate_atr\"\xee\x02\n" +
	"\bExtremum\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.marketanalyzer.v1.ExtremumKindR\x04kind\x12!\n" +
	"\fcandle_index\x18\x02 \x01(\rR\vcandleIndex\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12:\n" +
	"\x19confirmation_candle_index\x18\x05 \x01(\rR\x17confirmationCandleIndex\x12G\n" +
	"\x11confirmation_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10confirmationTime\x12?\n" +
	"\breversal\x18\a \x01(\v2#.marketanalyzer.v1.ReversalEvidenceR\breversal\"D\n" +
	"\rExtremaResult\x123\n" +
	"\x06points\x18\x01 \x03(\v2\x1b.marketanalyzer.v1.ExtremumR\x06points\"\xdd\x01\n" +
	"\vTrendResult\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.marketanalyzer.v1.TrendStateR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttolerance\x18\x03 \x01(\tR\ttolerance\x12'\n" +
	"\x0freference_close\x18\x04 \x01(\tR\x0ereferenceClose\x12:\n" +
	"\aextrema\x18\x05 \x01(\v2 .marketanalyzer.v1.ExtremaResultR\aextrema\"\xbf\x03\n" +
	"\tPriceZone\x12\x1f\n" +
	"\vlower_bound\x18\x01 \x01(\tR\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\tR\n" +
	"upperBound\x121\n" +
	"\x14representative_price\x18\x03 \x01(\tR\x13representativePrice\x12/\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1b.marketanalyzer.v1.ZoneRoleR\x04role\x12)\n" +
	"\x10extremum_indices\x18\x05 \x03(\rR\x0fextremumIndices\x126\n" +
	"\x17accepted_candle_indices\x18\x06 \x03(\rR\x15acceptedCandleIndices\x12\x1f\n" +
	"\vtouch_count\x18\a \x01(\rR\n" +
	"touchCount\x12D\n" +
	"\x10first_touch_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0efirstTouchTime\x12B\n" +
	"\x0flast_touch_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastTouchTime\"\x85\x02\n" +
	"\fLevelsResult\x122\n" +
	"\x05zones\x18\x01 \x03(\v2\x1c.marketanalyzer.v1.PriceZoneR\x05zones\x12:\n" +
	"\aextrema\x18\x02 \x01(\v2 .marketanalyzer.v1.ExtremaResultR\aextrema\x12.\n" +
	"\x03atr\x18\x03 \x01(\v2\x1c.marketanalyzer.v1.ATRResultR\x03atr\x12,\n" +
	"\x12maximum_zone_width\x18\x04 \x01(\tR\x10maximumZoneWidth\x12'\n" +
	"\x0freference_close\x18\x05 \x01(\tR\x0ereferenceClose\"\x87\x01\n" +
	"\rGetATRRequest\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12:\n" +
	"\bsettings\x18\x02 \x01(\v2\x1e.marketanalyzer.v1.ATRSettingsR\bsettings\"\xf0\x01\n" +
	"\x0eGetATRResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.marketanalyzer.v1.MetadataR\bmetadata\x123\n" +
	"\acandles\x18\x02 \x03(\v2\x19.marketanalyzer.v1.CandleR\acandles\x12:\n" +
	"\bsettings\x18\x03 \x01(\v2\x1e.marketanalyzer.v1.ATRSettingsR\bsettings\x124\n" +
	"\x06result\x18\x04 \x01(\v2\x1c.marketanalyzer.v1.ATRResultR\x06result\"\x88\x01\n" +
	"\x0eGetNATRRequest\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12:\n" +
	"\bsettings\x18\x02 \x01(\v2\x1e.marketanalyzer.v1.ATRSettingsR\bsettings\"\xf2\x01\n" +
	"\x0fGetNATRResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.marketanalyzer.v1.MetadataR\bmetadata\x123\n" +
	"\acandles\x18\x02 \x03(\v2\x19.marketanalyzer.v1.CandleR\acandles\x12:\n" +
	"\bsettings\x18\x03 \x01(\v2\x1e.marketanalyzer.v1.ATRSettingsR\bsettings\x125\n" +
	"\x06result\x18\x04 \x01(\v2\x1d.marketanalyzer.v1.NATRResultR\x06result\"\x8f\x01\n" +
	"\x11GetExtremaRequest\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12>\n" +
	"\bsettings\x18\x02 \x01(\v2\".marketanalyzer.v1.ExtremaSettingsR\bsettings\"\xfc\x01\n" +
	"\x12GetExtremaResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.marketanalyzer.v1.MetadataR\bmetadata\x123\n" +
	"\acandles\x18\x02 \x03(\v2\x19.marketanalyzer.v1.CandleR\acandles\x12>\n" +
	"\bsettings\x18\x03 \x01(\v2\".marketanalyzer.v1.ExtremaSettingsR\bsettings\x128\n" +
	"\x06result\x18\x04 \x01(\v2 .marketanalyzer.v1.ExtremaResultR\x06result\"\x8b\x01\n" +
	"\x0fGetTrendRequest\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12<\n" +
	"\bsettings\x18\x02 \x01(\v2 .marketanalyzer.v1.TrendSettingsR\bsettings\"\xf6\x01\n" +
	"\x10GetTrendResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.marketanalyzer.v1.MetadataR\bmetadata\x123\n" +
	"\acandles\x18\x02 \x03(\v2\x19.marketanalyzer.v1.CandleR\acandles\x12<\n" +
	"\bsettings\x18\x03 \x01(\v2 .marketanalyzer.v1.TrendSettingsR\bsettings\x126\n" +
	"\x06result\x18\x04 \x01(\v2\x1e.marketanalyzer.v1.TrendResultR\x06result\"\x8c\x01\n" +
	"\x10GetLevelsRequest\x12:\n" +
	"\tselection\x18\x01 \x01(\v2\x1c.marketanalyzer.v1.SelectionR\tselection\x12<\n" +
	"\bsettings\x18\x02 \x01(\v2 .marketanalyzer.v1.LevelSettingsR\bsettings\"\xf8\x01\n" +
	"\x11GetLevelsResponse\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.marketanalyzer.v1.MetadataR\bmetadata\x123\n" +
	"\acandles\x18\x02 \x03(\v2\x19.marketanalyzer.v1.CandleR\acandles\x12<\n" +
	"\bsettings\x18\x03 \x01(\v2 .marketanalyzer.v1.LevelSettingsR\bsettings\x127\n" +
	"\x06result\x18\x04 \x01(\v2\x1f.marketanalyzer.v1.LevelsResultR\x06result\"\xc8\x01\n" +
	"\vErrorDetail\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x19\n" +
	"\x05field\x18\x02 \x01(\tH\x00R\x05field\x88\x01\x01\x12(\n" +
	"\rupstream_code\x18\x03 \x01(\tH\x01R\fupstreamCode\x88\x01\x01\x12,\n" +
	"\x0fupstream_reason\x18\x04 \x01(\tH\x02R\x0eupstreamReason\x88\x01\x01B\b\n" +
	"\x06_fieldB\x10\n" +
	"\x0e_upstream_codeB\x12\n" +
	"\x10_upstream_reason*^\n" +
	"\vPriceSource\x12\x1c\n" +
	"\x18PRICE_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PRICE_SOURCE_CLOSE\x10\x01\x12\x19\n" +
	"\x15PRICE_SOURCE_HIGH_LOW\x10\x02*\\\n" +
	"\fExtremumKind\x12\x1d\n" +
	"\x19EXTREMUM_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXTREMUM_KIND_HIGH\x10\x01\x12\x15\n" +
	"\x11EXTREMUM_KIND_LOW\x10\x02*\x8b\x01\n" +
	"\n" +
	"TrendState\x12\x1b\n" +
	"\x17TREND_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTREND_STATE_UP\x10\x01\x12\x14\n" +
	"\x10TREND_STATE_DOWN\x10\x02\x12\x18\n" +
	"\x14TREND_STATE_SIDEWAYS\x10\x03\x12\x1c\n" +
	"\x18TREND_STATE_UNDETERMINED\x10\x04*n\n" +
	"\bZoneRole\x12\x19\n" +
	"\x15ZONE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ZONE_ROLE_SUPPORT\x10\x01\x12\x18\n" +
	"\x14ZONE_ROLE_RESISTANCE\x10\x02\x12\x16\n" +
	"\x12ZONE_ROLE_AT_PRICE\x10\x032\xc0\x03\n" +
	"\x15MarketAnalyzerService\x12M\n" +
	"\x06GetATR\x12 .marketanalyzer.v1.GetATRRequest\x1a!.marketanalyzer.v1.GetATRResponse\x12P\n" +
	"\aGetNATR\x12!.marketanalyzer.v1.GetNATRRequest\x1a\".marketanalyzer.v1.GetNATRResponse\x12Y\n" +
	"\n" +
	"GetExtrema\x12$.marketanalyzer.v1.GetExtremaRequest\x1a%.marketanalyzer.v1.GetExtremaResponse\x12S\n" +
	"\bGetTrend\x12\".marketanalyzer.v1.GetTrendRequest\x1a#.marketanalyzer.v1.GetTrendResponse\x12V\n" +
	"\tGetLevels\x12#.marketanalyzer.v1.GetLevelsRequest\x1a$.marketanalyzer.v1.GetLevelsResponseBOZMgithub.com/imbpp123/market-analyzer/api/go/marketanalyzer/v1;marketanalyzerv1b\x06proto3"

var (
	file_market_analyzer_proto_rawDescOnce sync.Once
	file_market_analyzer_proto_rawDescData []byte
)

func file_market_analyzer_proto_rawDescGZIP() []byte {
	file_market_analyzer_proto_rawDescOnce.Do(func() {
		file_market_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_analyzer_proto_rawDesc), len(file_market_analyzer_proto_rawDesc)))
	})
	return file_market_analyzer_proto_rawDescData
}

var file_market_analyzer_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_market_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_market_analyzer_proto_goTypes = []any{
	(PriceSource)(0),                // 0: marketanalyzer.v1.PriceSource
	(ExtremumKind)(0),               // 1: marketanalyzer.v1.ExtremumKind
	(TrendState)(0),                 // 2: marketanalyzer.v1.TrendState
	(ZoneRole)(0),                   // 3: marketanalyzer.v1.ZoneRole
	(*Selection)(nil),               // 4: marketanalyzer.v1.Selection
	(*ATRSettings)(nil),             // 5: marketanalyzer.v1.ATRSettings
	(*LocalExtremaSettings)(nil),    // 6: marketanalyzer.v1.LocalExtremaSettings
	(*PercentReversalSettings)(nil), // 7: marketanalyzer.v1.PercentReversalSettings
	(*ATRReversalSettings)(nil),     // 8: marketanalyzer.v1.ATRReversalSettings
	(*ExtremaSettings)(nil),         // 9: marketanalyzer.v1.ExtremaSettings
	(*TrendSettings)(nil),           // 10: marketanalyzer.v1.TrendSettings
	(*LevelSettings)(nil),           // 11: marketanalyzer.v1.LevelSettings
	(*Candle)(nil),                  // 12: marketanalyzer.v1.Candle
	(*Metadata)(nil),                // 13: marketanalyzer.v1.Metadata
	(*ATRResult)(nil),               // 14: marketanalyzer.v1.ATRResult
	(*NATRResult)(nil),              // 15: marketanalyzer.v1.NATRResult
	(*ReversalEvidence)(nil),        // 16: marketanalyzer.v1.ReversalEvidence
	(*Extremum)(nil),                // 17: marketanalyzer.v1.Extremum
	(*ExtremaResult)(nil),           // 18: marketanalyzer.v1.ExtremaResult
	(*TrendResult)(nil),             // 19: marketanalyzer.v1.TrendResult
	(*PriceZone)(nil),               // 20: marketanalyzer.v1.PriceZone
	(*LevelsResult)(nil),            // 21: marketanalyzer.v1.LevelsResult
	(*GetATRRequest)(nil),           // 22: marketanalyzer.v1.GetATRRequest
	(*GetATRResponse)(nil),          // 23: marketanalyzer.v1.GetATRResponse
	(*GetNATRRequest)(nil),          // 24: marketanalyzer.v1.GetNATRRequest
	(*GetNATRResponse)(nil),         // 25: marketanalyzer.v1.GetNATRResponse
	(*GetExtremaRequest)(nil),       // 26: marketanalyzer.v1.GetExtremaRequest
	(*GetExtremaResponse)(nil),      // 27: marketanalyzer.v1.GetExtremaResponse
	(*GetTrendRequest)(nil),         // 28: marketanalyzer.v1.GetTrendRequest
	(*GetTrendResponse)(nil),        // 29: marketanalyzer.v1.GetTrendResponse
	(*GetLevelsRequest)(nil),        // 30: marketanalyzer.v1.GetLevelsRequest
	(*GetLevelsResponse)(nil),       // 31: marketanalyzer.v1.GetLevelsResponse
	(*ErrorDetail)(nil),             // 32: marketanalyzer.v1.ErrorDetail
	(*timestamppb.Timestamp)(nil),   // 33: google.protobuf.Timestamp
}
var file_market_analyzer_proto_depIdxs = []int32{
	33, // 0: marketanalyzer.v1.Selection.to:type_name -> google.protobuf.Timestamp
	0,  // 1: marketanalyzer.v1.ExtremaSettings.price_source:type_name -> marketanalyzer.v1.PriceSource
	6,  // 2: marketanalyzer.v1.ExtremaSettings.local_extrema:type_name -> marketanalyzer.v1.LocalExtremaSettings
	7,  // 3: marketanalyzer.v1.ExtremaSettings.reversal_percent:type_name -> marketanalyzer.v1.PercentReversalSettings
	8,  // 4: marketanalyzer.v1.ExtremaSettings.reversal_atr:type_name -> marketanalyzer.v1.ATRReversalSettings
	9,  // 5: marketanalyzer.v1.TrendSettings.extrema:type_name -> marketanalyzer.v1.ExtremaSettings
	9,  // 6: marketanalyzer.v1.LevelSettings.extrema:type_name -> marketanalyzer.v1.ExtremaSettings
	33, // 7: marketanalyzer.v1.Candle.open_time:type_name -> google.protobuf.Timestamp
	33, // 8: marketanalyzer.v1.Candle.close_time:type_name -> google.protobuf.Timestamp
	33, // 9: marketanalyzer.v1.Candle.fetched_at:type_name -> google.protobuf.Timestamp
	4,  // 10: marketanalyzer.v1.Metadata.selection:type_name -> marketanalyzer.v1.Selection
	33, // 11: marketanalyzer.v1.Metadata.evaluated_at:type_name -> google.protobuf.Timestamp
	33, // 12: marketanalyzer.v1.Metadata.source_from:type_name -> google.protobuf.Timestamp
	33, // 13: marketanalyzer.v1.Metadata.source_to:type_name -> google.protobuf.Timestamp
	33, // 14: marketanalyzer.v1.ATRResult.value_time:type_name -> google.protobuf.Timestamp
	33, // 15: marketanalyzer.v1.NATRResult.value_time:type_name -> google.protobuf.Timestamp
	1,  // 16: marketanalyzer.v1.Extremum.kind:type_name -> marketanalyzer.v1.ExtremumKind
	33, // 17: marketanalyzer.v1.Extremum.time:type_name -> google.protobuf.Timestamp
	33, // 18: marketanalyzer.v1.Extremum.confirmation_time:type_name -> google.protobuf.Timestamp
	16, // 19: marketanalyzer.v1.Extremum.reversal:type_name -> marketanalyzer.v1.ReversalEvidence
	17, // 20: marketanalyzer.v1.ExtremaResult.points:type_name -> marketanalyzer.v1.Extremum
	2,  // 21: marketanalyzer.v1.TrendResult.state:type_name -> marketanalyzer.v1.TrendState
	18, // 22: marketanalyzer.v1.TrendResult.extrema:type_name -> marketanalyzer.v1.ExtremaResult
	3,  // 23: marketanalyzer.v1.PriceZone.role:type_name -> marketanalyzer.v1.ZoneRole
	33, // 24: marketanalyzer.v1.PriceZone.first_touch_time:type_name -> google.protobuf.Timestamp
	33, // 25: marketanalyzer.v1.PriceZone.last_touch_time:type_name -> google.protobuf.Timestamp
	20, // 26: marketanalyzer.v1.LevelsResult.zones:type_name -> marketanalyzer.v1.PriceZone
	18, // 27: marketanalyzer.v1.LevelsResult.extrema:type_name -> marketanalyzer.v1.ExtremaResult
	14, // 28: marketanalyzer.v1.LevelsResult.atr:type_name -> marketanalyzer.v1.ATRResult
	4,  // 29: marketanalyzer.v1.GetATRRequest.selection:type_name -> marketanalyzer.v1.Selection
	5,  // 30: marketanalyzer.v1.GetATRRequest.settings:type_name -> marketanalyzer.v1.ATRSettings
	13, // 31: marketanalyzer.v1.GetATRResponse.metadata:type_name -> marketanalyzer.v1.Metadata
	12, // 32: marketanalyzer.v1.GetATRResponse.candles:type_name -> marketanalyzer.v1.Candle
	5,  // 33: marketanalyzer.v1.GetATRResponse.settings:type_name -> marketanalyzer.v1.ATRSettings
	14, // 34: marketanalyzer.v1.GetATRResponse.result:type_name -> marketanalyzer.v1.ATRResult
	4,  // 35: marketanalyzer.v1.GetNATRRequest.selection:type_name -> marketanalyzer.v1.Selection
	5,  // 36: marketanalyzer.v1.GetNATRRequest.settings:type_name -> marketanalyzer.v1.ATRSettings
	13, // 37: marketanalyzer.v1.GetNATRResponse.metadata:type_name -> marketanalyzer.v1.Metadata
	12, // 38: marketanalyzer.v1.GetNATRResponse.candles:type_name -> marketanalyzer.v1.Candle
	5,  // 39: marketanalyzer.v1.GetNATRResponse.settings:type_name -> marketanalyzer.v1.ATRSettings
	15, // 40: marketanalyzer.v1.GetNATRResponse.result:type_name -> marketanalyzer.v1.NATRResult
	4,  // 41: marketanalyzer.v1.GetExtremaRequest.selection:type_name -> marketanalyzer.v1.Selection
	9,  // 42: marketanalyzer.v1.GetExtremaRequest.settings:type_name -> marketanalyzer.v1.ExtremaSettings
	13, // 43: marketanalyzer.v1.GetExtremaResponse.metadata:type_name -> marketanalyzer.v1.Metadata
	12, // 44: marketanalyzer.v1.GetExtremaResponse.candles:type_name -> marketanalyzer.v1.Candle
	9,  // 45: marketanalyzer.v1.GetExtremaResponse.settings:type_name -> marketanalyzer.v1.ExtremaSettings
	18, // 46: marketanalyzer.v1.GetExtremaResponse.result:type_name -> marketanalyzer.v1.ExtremaResult
	4,  // 47: marketanalyzer.v1.GetTrendRequest.selection:type_name -> marketanalyzer.v1.Selection
	10, // 48: marketanalyzer.v1.GetTrendRequest.settings:type_name -> marketanalyzer.v1.TrendSettings
	13, // 49: marketanalyzer.v1.GetTrendResponse.metadata:type_name -> marketanalyzer.v1.Metadata
	12, // 50: marketanalyzer.v1.GetTrendResponse.candles:type_name -> marketanalyzer.v1.Candle
	10, // 51: marketanalyzer.v1.GetTrendResponse.settings:type_name -> marketanalyzer.v1.TrendSettings
	19, // 52: marketanalyzer.v1.GetTrendResponse.result:type_name -> marketanalyzer.v1.TrendResult
	4,  // 53: marketanalyzer.v1.GetLevelsRequest.selection:type_name -> marketanalyzer.v1.Selection
	11, // 54: marketanalyzer.v1.GetLevelsRequest.settings:type_name -> marketanalyzer.v1.LevelSettings
	13, // 55: marketanalyzer.v1.GetLevelsResponse.metadata:type_name -> marketanalyzer.v1.Metadata
	12, // 56: marketanalyzer.v1.GetLevelsResponse.candles:type_name -> marketanalyzer.v1.Candle
	11, // 57: marketanalyzer.v1.GetLevelsResponse.settings:type_name -> marketanalyzer.v1.LevelSettings
	21, // 58: marketanalyzer.v1.GetLevelsResponse.result:type_name -> marketanalyzer.v1.LevelsResult
	22, // 59: marketanalyzer.v1.MarketAnalyzerService.GetATR:input_type -> marketanalyzer.v1.GetATRRequest
	24, // 60: marketanalyzer.v1.MarketAnalyzerService.GetNATR:input_type -> marketanalyzer.v1.GetNATRRequest
	26, // 61: marketanalyzer.v1.MarketAnalyzerService.GetExtrema:input_type -> marketanalyzer.v1.GetExtremaRequest
	28, // 62: marketanalyzer.v1.MarketAnalyzerService.GetTrend:input_type -> marketanalyzer.v1.GetTrendRequest
	30, // 63: marketanalyzer.v1.MarketAnalyzerService.GetLevels:input_type -> marketanalyzer.v1.GetLevelsRequest
	23, // 64: marketanalyzer.v1.MarketAnalyzerService.GetATR:output_type -> marketanalyzer.v1.GetATRResponse
	25, // 65: marketanalyzer.v1.MarketAnalyzerService.GetNATR:output_type -> marketanalyzer.v1.GetNATRResponse
	27, // 66: marketanalyzer.v1.MarketAnalyzerService.GetExtrema:output_type -> marketanalyzer.v1.GetExtremaResponse
	29, // 67: marketanalyzer.v1.MarketAnalyzerService.GetTrend:output_type -> marketanalyzer.v1.GetTrendResponse
	31, // 68: marketanalyzer.v1.MarketAnalyzerService.GetLevels:output_type -> marketanalyzer.v1.GetLevelsResponse
	64, // [64:69] is the sub-list for method output_type
	59, // [59:64] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_market_analyzer_proto_init() }
func file_market_analyzer_proto_init() {
	if File_market_analyzer_proto != nil {
		return
	}
	file_market_analyzer_proto_msgTypes[0].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[1].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[2].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[3].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[4].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[5].OneofWrappers = []any{
		(*ExtremaSettings_LocalExtrema)(nil),
		(*ExtremaSettings_ReversalPercent)(nil),
		(*ExtremaSettings_ReversalAtr)(nil),
	}
	file_market_analyzer_proto_msgTypes[6].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[7].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[8].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[12].OneofWrappers = []any{}
	file_market_analyzer_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_analyzer_proto_rawDesc), len(file_market_analyzer_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_analyzer_proto_goTypes,
		DependencyIndexes: file_market_analyzer_proto_depIdxs,
		EnumInfos:         file_market_analyzer_proto_enumTypes,
		MessageInfos:      file_market_analyzer_proto_msgTypes,
	}.Build()
	File_market_analyzer_proto = out.File
	file_market_analyzer_proto_goTypes = nil
	file_market_analyzer_proto_depIdxs = nil
}
