// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: market_analyzer.proto

package marketanalyzerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketAnalyzerService_GetATR_FullMethodName     = "/marketanalyzer.v1.MarketAnalyzerService/GetATR"
	MarketAnalyzerService_GetNATR_FullMethodName    = "/marketanalyzer.v1.MarketAnalyzerService/GetNATR"
	MarketAnalyzerService_GetExtrema_FullMethodName = "/marketanalyzer.v1.MarketAnalyzerService/GetExtrema"
	MarketAnalyzerService_GetTrend_FullMethodName   = "/marketanalyzer.v1.MarketAnalyzerService/GetTrend"
	MarketAnalyzerService_GetLevels_FullMethodName  = "/marketanalyzer.v1.MarketAnalyzerService/GetLevels"
)

// MarketAnalyzerServiceClient is the client API for MarketAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketAnalyzerServiceClient interface {
	GetATR(ctx context.Context, in *GetATRRequest, opts ...grpc.CallOption) (*GetATRResponse, error)
	GetNATR(ctx context.Context, in *GetNATRRequest, opts ...grpc.CallOption) (*GetNATRResponse, error)
	GetExtrema(ctx context.Context, in *GetExtremaRequest, opts ...grpc.CallOption) (*GetExtremaResponse, error)
	GetTrend(ctx context.Context, in *GetTrendRequest, opts ...grpc.CallOption) (*GetTrendResponse, error)
	GetLevels(ctx context.Context, in *GetLevelsRequest, opts ...grpc.CallOption) (*GetLevelsResponse, error)
}

type marketAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketAnalyzerServiceClient(cc grpc.ClientConnInterface) MarketAnalyzerServiceClient {
	return &marketAnalyzerServiceClient{cc}
}

func (c *marketAnalyzerServiceClient) GetATR(ctx context.Context, in *GetATRRequest, opts ...grpc.CallOption) (*GetATRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetATRResponse)
	err := c.cc.Invoke(ctx, MarketAnalyzerService_GetATR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketAnalyzerServiceClient) GetNATR(ctx context.Context, in *GetNATRRequest, opts ...grpc.CallOption) (*GetNATRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNATRResponse)
	err := c.cc.Invoke(ctx, MarketAnalyzerService_GetNATR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketAnalyzerServiceClient) GetExtrema(ctx context.Context, in *GetExtremaRequest, opts ...grpc.CallOption) (*GetExtremaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtremaResponse)
	err := c.cc.Invoke(ctx, MarketAnalyzerService_GetExtrema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketAnalyzerServiceClient) GetTrend(ctx context.Context, in *GetTrendRequest, opts ...grpc.CallOption) (*GetTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendResponse)
	err := c.cc.Invoke(ctx, MarketAnalyzerService_GetTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketAnalyzerServiceClient) GetLevels(ctx context.Context, in *GetLevelsRequest, opts ...grpc.CallOption) (*GetLevelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLevelsResponse)
	err := c.cc.Invoke(ctx, MarketAnalyzerService_GetLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketAnalyzerServiceServer is the server API for MarketAnalyzerService service.
// All implementations must embed UnimplementedMarketAnalyzerServiceServer
// for forward compatibility.
type MarketAnalyzerServiceServer interface {
	GetATR(context.Context, *GetATRRequest) (*GetATRResponse, error)
	GetNATR(context.Context, *GetNATRRequest) (*GetNATRResponse, error)
	GetExtrema(context.Context, *GetExtremaRequest) (*GetExtremaResponse, error)
	GetTrend(context.Context, *GetTrendRequest) (*GetTrendResponse, error)
	GetLevels(context.Context, *GetLevelsRequest) (*GetLevelsResponse, error)
	mustEmbedUnimplementedMarketAnalyzerServiceServer()
}

// UnimplementedMarketAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketAnalyzerServiceServer struct{}

func (UnimplementedMarketAnalyzerServiceServer) GetATR(context.Context, *GetATRRequest) (*GetATRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetATR not implemented")
}
func (UnimplementedMarketAnalyzerServiceServer) GetNATR(context.Context, *GetNATRRequest) (*GetNATRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNATR not implemented")
}
func (UnimplementedMarketAnalyzerServiceServer) GetExtrema(context.Context, *GetExtremaRequest) (*GetExtremaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtrema not implemented")
}
func (UnimplementedMarketAnalyzerServiceServer) GetTrend(context.Context, *GetTrendRequest) (*GetTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrend not implemented")
}
func (UnimplementedMarketAnalyzerServiceServer) GetLevels(context.Context, *GetLevelsRequest) (*GetLevelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevels not implemented")
}
func (UnimplementedMarketAnalyzerServiceServer) mustEmbedUnimplementedMarketAnalyzerServiceServer() {}
func (UnimplementedMarketAnalyzerServiceServer) testEmbeddedByValue()                               {}

// UnsafeMarketAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketAnalyzerServiceServer will
// result in compilation errors.
type UnsafeMarketAnalyzerServiceServer interface {
	mustEmbedUnimplementedMarketAnalyzerServiceServer()
}

func RegisterMarketAnalyzerServiceServer(s grpc.ServiceRegistrar, srv MarketAnalyzerServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketAnalyzerService_ServiceDesc, srv)
}

func _MarketAnalyzerService_GetATR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetATRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAnalyzerServiceServer).GetATR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAnalyzerService_GetATR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAnalyzerServiceServer).GetATR(ctx, req.(*GetATRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketAnalyzerService_GetNATR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNATRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAnalyzerServiceServer).GetNATR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAnalyzerService_GetNATR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAnalyzerServiceServer).GetNATR(ctx, req.(*GetNATRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketAnalyzerService_GetExtrema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtremaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAnalyzerServiceServer).GetExtrema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAnalyzerService_GetExtrema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAnalyzerServiceServer).GetExtrema(ctx, req.(*GetExtremaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketAnalyzerService_GetTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAnalyzerServiceServer).GetTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAnalyzerService_GetTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAnalyzerServiceServer).GetTrend(ctx, req.(*GetTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketAnalyzerService_GetLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAnalyzerServiceServer).GetLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAnalyzerService_GetLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAnalyzerServiceServer).GetLevels(ctx, req.(*GetLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketAnalyzerService_ServiceDesc is the grpc.ServiceDesc for MarketAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketanalyzer.v1.MarketAnalyzerService",
	HandlerType: (*MarketAnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetATR",
			Handler:    _MarketAnalyzerService_GetATR_Handler,
		},
		{
			MethodName: "GetNATR",
			Handler:    _MarketAnalyzerService_GetNATR_Handler,
		},
		{
			MethodName: "GetExtrema",
			Handler:    _MarketAnalyzerService_GetExtrema_Handler,
		},
		{
			MethodName: "GetTrend",
			Handler:    _MarketAnalyzerService_GetTrend_Handler,
		},
		{
			MethodName: "GetLevels",
			Handler:    _MarketAnalyzerService_GetLevels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_analyzer.proto",
}
